apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::000654207548:role/sagemaker-kubeflow-test-eks-kfsgm-cluster-workers"
      "username": "system:node:{{EC2PrivateDNSName}}"


